
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const OPEN_REGISTER_USER = "OPEN_REGISTER_USER";
export const CLOSE_REGISTER_USER = "CLOSE_REGISTER_USER";
export const OPEN_EDIT_USER = "OPEN_EDIT_USER";
export const CLOSE_EDIT_USER = "CLOSE_EDIT_USER";
export const OPEN_DELETE_USER = "OPEN_DELETE_USER";
export const CLOSE_DELETE_USER = "CLOSE_DELETE_USER";


export const OPEN_CREATE_PLANEMAKE = "OPEN_CREATE_PLANEMAKE";
export const CLOSE_CREATE_PLANEMAKE = "CLOSE_CREATE_PLANEMAKE";
export const OPEN_EDIT_PLANEMAKE = "OPEN_EDIT_PLANEMAKE";
export const CLOSE_EDIT_PLANEMAKE = "CLOSE_EDIT_PLANEMAKE";
export const OPEN_DELETE_PLANEMAKE = "OPEN_DELETE_PLANEMAKE";
export const CLOSE_DELETE_PLANEMAKE = "CLOSE_DELETE_PLANEMAKE";


export const OPEN_CREATE_PLANEMODEL = "OPEN_CREATE_PLANEMODEL";
export const CLOSE_CREATE_PLANEMODEL = "CLOSE_CREATE_PLANEMODEL";
export const OPEN_EDIT_PLANEMODEL = "OPEN_EDIT_PLANEMODEL";
export const CLOSE_EDIT_PLANEMODEL = "CLOSE_EDIT_PLANEMODEL";
export const OPEN_DELETE_PLANEMODEL = "OPEN_DELETE_PLANEMODEL";
export const CLOSE_DELETE_PLANEMODEL = "CLOSE_DELETE_PLANEMODEL";


export const OPEN_CREATE_PLANESPOTTINGS = "OPEN_CREATE_PLANESPOTTINGS";
export const CLOSE_CREATE_PLANESPOTTINGS = "CLOSE_CREATE_PLANESPOTTINGS";
export const OPEN_EDIT_PLANESPOTTINGS = "OPEN_EDIT_PLANESPOTTINGS";
export const CLOSE_EDIT_PLANESPOTTINGS = "CLOSE_EDIT_PLANESPOTTINGS";
export const OPEN_DELETE_PLANESPOTTINGS = "OPEN_DELETE_PLANESPOTTINGS";
export const CLOSE_DELETE_PLANESPOTTINGS = "CLOSE_DELETE_PLANESPOTTINGS";


export const OPEN_CREATE_PLANE = "OPEN_CREATE_PLANE";
export const CLOSE_CREATE_PLANE = "CLOSE_CREATE_PLANE";
export const OPEN_EDIT_PLANE = "OPEN_EDIT_PLANE";
export const CLOSE_EDIT_PLANE = "CLOSE_EDIT_PLANE";
export const OPEN_DELETE_PLANE = "OPEN_DELETE_PLANE";
export const CLOSE_DELETE_PLANE = "CLOSE_DELETE_PLANE";