
export const CREATE_PLANEMAKE = "CREATE_PLANEMAKE";
export const UPDATE_PLANEMAKE = "UPDATE_PLANEMAKE";
export const DELETE_PLANEMAKE = "DELETE_PLANEMAKE";
export const GET_PLANEMAKES = "GET_PLANEMAKES";
export const SET_SELECTED_PLANEMAKE = "SET_SELECTED_PLANEMAKE";

export const CREATE_PLANEMODEL = "CREATE_PLANEMODEL";
export const UPDATE_PLANEMODEL = "UPDATE_PLANEMODEL";
export const DELETE_PLANEMODEL = "DELETE_PLANEMODEL";
export const GET_PLANEMODELS = "GET_PLANEMODELS";
export const SET_SELECTED_PLANEMODEL = "SET_SELECTED_PLANEMODEL";

export const CREATE_PLANE = "CREATE_PLANE";
export const UPDATE_PLANE = "UPDATE_PLANE";
export const DELETE_PLANE = "DELETE_PLANE";
export const GET_PLANES = "GET_PLANES";
export const SET_SELECTED_PLANE = "SET_SELECTED_PLANE";

export const CREATE_PLANESPOTTINGS = "CREATE_PLANESPOTTINGS";
export const UPDATE_PLANESPOTTINGS = "UPDATE_PLANESPOTTINGS";
export const DELETE_PLANESPOTTINGS = "DELETE_PLANESPOTTINGS";
export const GET_PLANESPOTTINGS = "GET_PLANESPOTTINGS";
export const SET_SELECTED_PLANESPOTTING = "SET_SELECTED_PLANESPOTTING";

export const SET_RECENT_PLANE_SPOTTINGS = "SET_RECENT_PLANE_SPOTTINGS";
export const SET_PLANE_SPOTTINGS_BY_MAKE = "SET_PLANE_SPOTTINGS_BY_MAKE";
export const SET_PLANE_SPOTTINGS_BY_MODEL = "SET_PLANE_SPOTTINGS_BY_MODEL";
export const SET_PLANE_SPOTTINGS_BY_PLANE = "SET_PLANE_SPOTTINGS_BY_PLANE";
